###

GET http://localhost:3000/user

###

GET http://localhost:3000/user?name=John%20Doe


###

GET http://localhost:3000/user/1234567891


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "testUser@test.com",
    "password": "1234567890"
}
###

POST http://localhost:3000/user
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3YzA2YzA4NGU3NDE5YjIyNDBmMzgiLCJpYXQiOjE3MDU0OTU3NzksImV4cCI6MTcwNTQ5OTM3OX0.T0hYoz-WxHscyrWvKlHTEeuVj5Ltlb4IA9-SW4AqFV4

{
    "_id": "65a7c06c084e7419b2240f38"
}

###

GET http://localhost:3000/user
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3YzA2YzA4NGU3NDE5YjIyNDBmMzgiLCJpYXQiOjE3MDU0OTU3NzksImV4cCI6MTcwNTQ5OTM3OX0.T0hYoz-WxHscyrWvKlHTEeuVj5Ltlb4IA9-SW4AqFV4

{
    "_id": "65a7c06c084e7419b2240f38"
}

###

GET http://localhost:3000/user
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3YzA2YzA4NGU3NDE5YjIyNDBmMzgiLCJpYXQiOjE3MDU0OTU3NzksImV4cCI6MTcwNTQ5OTM3OX0.T0hYoz-WxHscyrWvKlHTEeuVj5Ltlb4IA9-SW4AqFV4

{
    
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "1234567890",
    "firstName": "Johna",
    "lastName": "Doa"
}